# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maicon Pinto
email: maiconsilva.pinto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Meu nome é Maicon Silva Pinto, 27 anos, casado, pai de duas meninas. Programador PHP, trabalho desenvolvendo sites e sistemas para web.
  Conhecimento e experiência utilizando framework CakePHP, além de temas para Wordpress.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maiconpinto.com.br" # the base hostname & protocol for your site
twitter_username: maiconpinto
github_username:  maiconpinto

# Build settings
markdown: kramdown
